const express = require('express');
const router = express.Router();
const departmentController = require('../controllers/departmentController');
router.get('/', departmentController.getAllDepartments);
router.post('/', departmentController.createDepartment);
router.put('/:id', departmentController.updateDepartment);
router.delete('/:id', departmentController.deleteDepartment);
router.get('/:id/usage', departmentController.checkDepartmentUsage);
router.post('/:id/transfer-and-delete', departmentController.transferAndDeleteDepartment);
router.post('/:id/import-excel', departmentController.importDepartmentsFromExcel);
module.exports = router;
